name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: npx @11ty/eleventy

      - name: Install Python package modal
        run: pip install modal

      - name: Deploy to modal app
        run: |
          modal deploy main.py
